permissions:
  contents: write
  pages: write
  id-token: write
  deployments: write
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '19'

      - name: Install dependencies
        run: npm ci

      - name: Build the app
        run: |
          export PUBLIC_URL="https://kuinox.github.io/pokedex_react"
          npm run build
          
      - name: Setup Pages
        uses: actions/configure-pages@v2

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v1.0.4
        with:
          path: 'build'
      - name: Deploy GitHub Pages site
        uses: actions/deploy-pages@v1.2.2